sf_username=dummy
sf_password=dummy
sf_url=https://login.salesforce.com 
new_lead_url=https://orgfarm-c4666d5694-dev-ed.develop.lightning.force.com/lightning/o/Lead/new
leads_list_view_url=https://orgfarm-c4666d5694-dev-ed.develop.lightning.force.com/lightning/o/Lead/list?filterName=AllOpenLeads
help_portal_url=https://help.salesforce.com/s/
openai_model=gpt-4o-mini
chrome_profile_dir=chrome-profile
element_wait_timeout=15